<?php 
session_set_cookie_params(0);
session_start();
require("Contr_class_praticien.php");
contr_prat::cadenas_user();
require("Contr_class_pec.php");
contr_pec::create_pec();
require("vue/creation_pec.php");
?>