<?php 
session_set_cookie_params(0);
session_start();
require("modele/cadenas_user.php");
cadenas_user();
require("modele/modele_creation_pec.php");
create_pec();
require("vue/creation_pec.php");
?>