<?php 
session_start();
require("Contr_class_rdv.php");
require("Contr_class_praticien.php");
require("Contr_class_user.php");
contr_prat::cadenas_user();
contr_user::listing_users();
contr_rdv::creation_rdv();
require("vue/creation_rdv.php");
?>