<?php 
session_set_cookie_params(0);
session_start();
require("modele/cadenas_user.php");
require('modele/modele_compte_prat.php');
cadenas_user();
read_infos_prat();
require("vue/compte_prat.php");
?>