<?php 
session_set_cookie_params(0);
session_start();
require("Contr_class_user.php");
contr_user::cadenas_prat();
require("Contr_class_rdv.php");
contr_rdv::listing_rdv_user_id();
contr_rdv::suppr_rdv_user();
require("vue/liste_rdv_user.php");
?>